.travis.yml, Makefile, appveyor.yml, build.ps1, support/ci/appveyor.bat, support/ci/appveyor.ps1, support/ci/compile_libarchive.sh, support/ci/compile_libsodium.sh, support/ci/compile_zmq.sh, support/ci/fast_pass.sh, support/ci/install_rustfmt.sh, support/ci/lint.sh, support/ci/rust_env.sh, support/ci/rust_tests.sh
=> adding ci scripts

Cargo.toml, components/core/Cargo.toml, components/win-users/build.rs
=> core crate compiles under linux now

components/core/src/crypto/keys/box_key_pair.rs, components/core/src/crypto/keys/mod.rs, components/core/src/crypto/keys/sig_key_pair.rs
Signed-off-by: Elliott Davis <elliott@excellent.io>
=> Add function to decrypt with a given set of keys instead of using the key cache dir

components/core/src/crypto/keys/box_key_pair.rs, components/core/src/crypto/keys/mod.rs
Signed-off-by: Elliott Davis <elliott@excellent.io>
=> Add ability to convert key string to BoxKeyPair

components/core/src/output.rs
Signed-off-by: Jamie Winsor <jamie@vialstudios.com>
=> Fix rutime error when using output vs outputln

components/core/src/package/install.rs
There are 2 fixes in this changeset, both of which impact the way the `PATH` metafile is used and how older Habitat packages are treated by current tooling like the `hab` CLI, exporters, and the Supervisor.
This change restores the previous implementation of the
`PackageInstall#paths()` method to return path entries directly from the
`PATH` metafile and to not use the `RUNTIME_ENVIRONMENT` metafile.
As referenced in habitat-sh/builder#240, the semantic meaning of the
`PATH` metafile is precise and distinct from the newer
`RUNTIME_ENVIRONMENT` metafile. The path entries in a `PATH` metafile
are a one-to-one mapping with the values in the `$pkg_bin_dirs` Plan
variable which created the package. That is, the path entries in `PATH`
should only refer to directories under the package's own …
=> [core] Fix 2 issues with interpretation and use of `PATH` metafiles

components/core/src/package/install.rs
This change deals with an issue where the test suite was creating
incorrect data for `PATH` metafiles (they contained FS_ROOT path
prefixes) which caused the implementation of `PackageInstall#paths()` to
incorrectly pass when it should have failed. When looking at the testing
setups, a more real package installation would have better revealed the
bug so the test suite was refactored to create full install paths with a
temporary FS_ROOT, for example:
`/tmp/fs-root.Xxabc123efd/hab/pkg/acme/hotel/1.0.0/20180410160423` where
`/tmp/fs-root.Xxabc123efd` is the FS_ROOT.
=> [core] Account for FS_ROOT in `PackageInstall#paths()` & refactor tests.

.travis.yml, support/ci/compile_libsodium.sh, support/ci/rust_env.sh
=> A few tweaks to ensure rustfmt works properly

components/core/src/error.rs, components/core/src/package/install.rs, components/core/src/package/metadata.rs, components/core/src/service.rs
Support of https://github.com/habitat-sh/habitat/pull/5024; read that and commit messages here for further details.
=> Add BindingMode

components/core/src/lib.rs, components/core/src/output.rs
See https://github.com/habitat-sh/habitat/pull/5033 for details
=> Updates to support JSON logging

components/http-client/src/api_client.rs
We need to update the http client timeout and make it configurable in order to support uploading large files to the depot.
Signed-off-by: Salim Alam <salam@chef.io>
=> Update http client timeout, add env

components/core/src/package/install.rs
A concurrent change to habitat/habitat-sh will create temporary
directories during package installation with the naming scheme
.hab-pkg-install-RELEASE-RANDOM_ASCII (see habitat-sh/habitat#5369).
Other commands should ignore these directories when generating lists
of releases as they are either:
(1) The result of incomplete package installations that were killed; or,
(2) The result of a concurrently running package installation and will
soon be renamed.
Signed-off-by: Steven Danna <steve@chef.io>
=> Ignore temporary installation directories

components/core/src/package/plan.rs
Closes https://github.com/habitat-sh/builder/issues/368
=> Make plan parsing a little more robust.

.travis.yml, components/core/src/crypto/keys/box_key_pair.rs, components/core/src/crypto/keys/mod.rs, components/core/src/event.rs, components/core/src/os/process/windows_child.rs, components/core/src/package/archive.rs, components/core/src/package/ident.rs, components/core/src/package/install.rs, components/core/src/package/metadata.rs, components/http-client/src/net.rs
https://blog.rust-lang.org/2018/08/02/Rust-1.28.html
=> [ci,rustfmt] Formatting due to rustfmt 0.8.2 in Rust 1.28.0.

Cargo.lock
Signed-off-by: Christopher Maier <cmaier@chef.io>
=> [Maintenance] Update cargo dependencies

Cargo.lock, components/win-users/Cargo.toml, components/win-users/src/account.rs, components/win-users/src/sid.rs
bumping the winapi crate that has lots of namespace changes.
=> bump winapi crate

Cargo.lock, components/core/src/os/users/linux.rs
=> Update Cargo.lock and make necessary changes for new users crate API

components/core/src/os/signals/unix.rs
Resolves https://github.com/habitat-sh/core/issues/11
With the supervisor running, if we execute
```
➤ pkill -USR1 hab-sup; pkill -USR2 hab-sup
```
Before:
```
Received invalid signal: #12
```
After:
```
Received invalid signal: #10
Received invalid signal: #12
```
=> When multiple signals are received, return them in order; don't drop any

.travis.yml
https://blog.rust-lang.org/2018/09/25/Rust-1.29.1.html
=> [ci] Update to Rust 1.29.1.

components/core/src/package/list.rs
To be used in a `hab pkg list` command
=> Export package_list_for_origin

Cargo.lock
Signed-off-by: Matthew Peck <mpeck@chef.io>
=> update cargo lock post 0.66.0 release

components/core/src/package/ident.rs
It matches by the parts of PackageIdent, using our custom
`version` matches and lexicographic ordering otherwise
NOTE.  Out of scope is looking at the current implementation of Ord/PartialOrd/PartialEq which is confusing and gives some concerns (I don't think the generated PartialEq will match PartialOrd) but I'd rather tackle replacing that separately as there are insufficient tests around it to just replace.
=> Add a natural ordering of PackageIdents

Cargo.lock, components/core/Cargo.toml, components/core/src/crypto/artifact.rs, components/core/src/crypto/keys/box_key_pair.rs, components/core/src/crypto/keys/mod.rs, components/core/src/crypto/keys/sig_key_pair.rs, components/core/src/crypto/keys/sym_key.rs, components/core/src/lib.rs, components/core/src/package/install.rs, components/core/src/package/list.rs, components/core/src/package/metadata.rs, components/core/src/util/posix_perm.rs
> Linked to #82 
cc @christophermaier 
Signed-off-by: Romain Sertelon <romain@sertelon.fr>
=> Uses tempfile instead of tempdir

.travis.yml
https://blog.rust-lang.org/2018/10/25/Rust-1.30.0.html
=> Bump to rust 1.30.0

Cargo.lock
=> cargo update post 0.70.0 release

.travis.yml, components/core/src/crypto/artifact.rs, components/core/src/crypto/keys/box_key_pair.rs, components/core/src/crypto/keys/mod.rs, components/core/src/crypto/keys/sig_key_pair.rs, components/core/src/crypto/keys/sym_key.rs, components/core/src/fs.rs, components/core/src/os/signals/windows.rs, components/core/src/package/archive.rs, components/core/src/package/install.rs, components/core/src/package/metadata.rs
=> Update to Rust 1.31.0

Cargo.lock, components/win-users/src/account.rs
=> update cargo locks

components/core/src/service.rs
This is required for https://github.com/habitat-sh/habitat/pull/5890
@cm @baumanj have already initially reviewed the above PR and therefore will have some context on this change.
Signed-off-by: Jeremy J. Miller <jm@chef.io>
=> adding service HealthCheckInterval implementation

Cargo.lock
=> Update Cargo.lock for hab 0.73.0

CODEOWNERS
=> Add jamesc to some code areas in CODEOWNERS

components/core/src/crypto/keys/sym_key.rs
SymKeys are currently declared to have a public key type of `()` due
to their being a monomorphization of the `KeyPair<P,S>` type. When
creating a new `SymKey`, you can either pass a "public key" of
`Some(())` or `None`, which is arguably more correct (given the
existing `KeyPair` typing, that is... addressing that would be a
larger refactoring).
By embracing the `None`, we get to eliminate the (private)
`get_public_key` method (which is very confusing in this context), as
well as greatly simplify the implementation of `get_pair_for`.
Hat tip to @baumanj for this!
This commit contains a partial reversion of commit
971f5efb3b65f716eba062937321e791fb7f11b2.
Signed-off-by: Christopher Maier <cmaier@chef.io>
=> SymKeys don't have public keys, so don't pretend they do

.travis.yml, components/core/src/config.rs, components/core/src/crypto/artifact.rs, components/core/src/crypto/keys/box_key_pair.rs, components/core/src/crypto/keys/mod.rs, components/core/src/crypto/keys/sig_key_pair.rs, components/core/src/crypto/keys/sym_key.rs, components/core/src/os/process/windows_child.rs, components/core/src/util/posix_perm.rs, components/core/src/util/win_perm.rs
=> Rust 1.32.0

components/core/src/fs.rs
The Habitat code has a number of places where it writes to a temporary
file and then renames the file. The goal of this pattern is to achieve
an atomic write to the file to prevent concurrent readers from seeing
incomplete versions of this file.
However, getting this pattern right can be tricky. For example, the
temporary file must be created in the same directory to ensure an
atomic rename is possible and the temporary file must by fsync'd to
disk before the rename to protect against seeing partial files in some
powerloss scenarios.
The AtomicWriter is an attempt to help us get this pattern right
across the code base.
Signed-off-by: Steven Danna <steve@chef.io>
=> Add fs::AtomicWriter and fs::atomic_write

components/core/Cargo.toml, components/http-client/Cargo.toml, components/win-users/Cargo.toml
The current values are inconsistent and don't accurately reflect the real authors of the current code.
=> Set Cargo.toml authors = ["The Habitat Maintainers <humans@habitat.sh>"]

components/core/src/fs.rs
In the PR that introduced AtomicWriter, we removed this pretty early
in the review process.  Here I've written up various bits of investigation
I've done about whether we need to fsync the directory so we can make
an informed decision about whether to leave it out.
---
To ensure that the rename() has been committed to disk, we must call
fsync() on the containing directory. Without this fsync() call,
powerloss (or VM reset, or crash), could result in data loss. Thus,
this affects the durability of the AtomicWriter but not the atomicity
as far as I know.
Not all filesystems support fsync() on directories. For instance, some
filesystems don't even define the fsync operation on directory
descriptors. In this case Linux returns EINVAL: …
=> [AtomicWriter] fsync() parent directory after rename

.travis.yml, components/core/src/output.rs, components/core/src/package/install.rs
=> Update to rust 1.33.0

Cargo.lock
See https://github.com/habitat-sh/habitat/issues/6284
=> Cargo update following release 0.78.0

components/core/Cargo.toml, components/http-client/Cargo.toml
=> [http-client] Annotate version pins in `Cargo.toml`.
