components/core/src/event.rs

This is in preperation for adding OriginEncryptionKeyUpload
Signed-off-by: Travis Elliott Davis <edavis@chef.io>

Rename Event OriginSecretKeyUpload to OriginSigningKeyUpload

---

components/core/src/os/users/windows.rs

Windows does not have the Linux concept of groups. So any value passed here to validate a group will either be empty or a dummy/meaningless string. We should always "succeed" by passing an empty string which windows implementations will never act on.
This addresses https://github.com/habitat-sh/habitat/issues/4685 allowing windows plans to leave out `$pkg_svc_group`. Without this change, users would need to include that when wanting to run under a non default `pkg_svc_user` and set it to a valid user. And well...thats pretty darn silly.

getting gid on windows should be a no-op

---

components/core/src/os/process/linux.rs
components/core/src/os/process/mod.rs
components/core/src/os/signals/mod.rs
components/core/src/os/signals/unix.rs

This will allow us to reap zombies when running the Launcher as PID 1. 
Without this, zombie processes would build up on a system, eventually 
filling up the process table. This would be a Bad Thing (TM).
While explicitly ignoring `SIGCHLD` with `SIG_IGN` would eliminate the
zombie problem, we would run into problems when the child process is
the Supervisor! We may need to restart it, so we have to actually
handle `SIGCHLD`.
Signed-off-by: Christopher Maier <cmaier@chef.io>

Set up a SIGCHLD handler on Linux

---

.travis.yml
CODEOWNERS
Cargo.lock
Cargo.toml
Makefile
components/http-client/Cargo.toml
components/http-client/build.rs
components/http-client/src/api_client.rs
components/http-client/src/error.rs
components/http-client/src/lib.rs
components/http-client/src/net.rs
components/http-client/src/proxy.rs
components/http-client/src/util.rs

Part of habitat-sh/habitat#4726; see that for context.
Follow-on PRs for converting `habitat-sh/habitat` and `habitat-sh/builder` to use this will come next.

Add http-client crate

---

components/core/src/fs.rs
components/core/src/os/process/windows_child.rs

This ensures that the default `FS_ROOT` on windows ends in `\`. While almost all apps on windows handle forward slashes just as well as backslashes there are a few (like SQL Server 2016 (unlike 2017)) that may not understand forward slashes. This should fix those cases.

 Use a backslash for windows FS_ROOT and PKG_PATH

---

components/core/src/os/users/linux.rs

This PR is required to resolve https://github.com/habitat-sh/habitat/issues/4716
Exposes the members of the `group` struct from the user crate so that we can validate in the hab binary on studio entrance 
Signed-off-by: Ian Henry <ihenry@chef.io>

Exposes members from group struct via new fn

---

components/core/src/package/ident.rs

This change will be used in the install logic in common to better
express fully qualified package identifiers by type.

[core] Implement `Cow<'a, PackageIdent>` for `PackageIdent`.

---

components/core/src/package/install.rs

This change attempts to provide an answer when calling
`PacakgeInstall#paths()` on Windows-built packages after the Habitat
0.53.0 release on 2018-02-05. After this point the build program wasn't
creating a `PATH` metafile which is required by some core logic when
finding programs in packages, etc.
The `PATH` metafile creation was restored for Windows builds in
abitat-sh/habitat#895 and this change tries to deal with all Windows
packages built between these 2 events.
The `PATH` value in a present `RUNTIME_ENVIRONMENT` metafile will be
used if such a metafile is present, and otherwise falls back to
returning an empty `Vec<PathBuf>` as expected. A unit test attempting to
cover this edge case is also provided here.
As this edge case addresses a small number of packages, this commit can …

[core] Add temporary Windows fallback in PackageInstall#paths().

---

components/core/src/crypto/hash.rs
components/http-client/src/api_client.rs

Removes the following warnings:
```
warning: unnecessary parentheses around function argument
--> components/core/src/crypto/hash.rs:42:28
|
42 |     let mut st = vec![0u8; (unsafe { libsodium_sys::crypto_generichash_statebytes() })];
|                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
|
= note: #[warn(unused_parens)] on by default
warning: unnecessary parentheses around function argument
--> components/core/src/crypto/hash.rs:56:28
|
56 |     let mut st = vec![0u8; (unsafe { libsodium_sys::crypto_generichash_statebytes() })];
|                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
warning: unnecessary parentheses around function argument
--> …
```

Remove compiler warnings in `core` & `http-client`

---

components/core/src/package/install.rs
components/core/src/package/metadata.rs

This change introduces a net-new metafile in a package, called
`RUNTIME_PATH`. Its contents are a path separator-delimited collection
of path elements that need to be added to an environment's `$PATH`
(`$env:PATH` on Windows) before to command can be expected to run
correctly. Prior to this change, the location for this information was
in the `RUNTIME_ENVIRONMENT` metafile (or was dynamically computed using
fallback logic using `PATH`, `DEPS`, and `TDEPS` metafiles). Upstream
changes to the build program have split the PATH computing logic apart
from the RUNTIME_ENVIRONMENT layering logic which let us to introducing
a standalone piece of package metadata to represent this.
RUNTIME_PATH metafile
---------------------
(The following will be added to the reference documentation in the …

[core] Introduce `RUNTIME_PATH` metafile support in `PackageInstall`.

---

components/http-client/src/api_client.rs

This change adds an option for bypassing SSL cert validation to the hab client. This can be useful as a workaround or for test purposes when working with self-signed or internal corp certificates that have not yet been added to the root trust chain. 
Signed-off-by: Salim Alam <salam@chef.io>

Add option for bypassing cert validation

---

components/core/src/package/target.rs

Represents an **older** [Linux kernel]-based system from the 2.6.x
family running on a [64-bit] version of the [x86][x] [instruction set
architecture][isa], commonly known as [x86_64].
This Habitat package target is intended for software with older
buildtime or runtime requirements than those supported by the current
`x86_64-linux` package target. Specifically, software with this package
target should run on systems from around the year 2016, when the Habitat
project was publicly launched. This Habitat package target will run on
Linux systems equipped with kernel versions as low as 2.6.32.
[Linux kernel]: https://en.wikipedia.org/wiki/Linux_kernel
[64-bit]: https://en.wikipedia.org/wiki/64-bit_computing
[x]: https://en.wikipedia.org/wiki/X86
[isa]: …

[core] Introduce a new `x86_64-linux-kernel2` `PackageTarget`.

---

.travis.yml

https://blog.rust-lang.org/2018/07/10/Rust-1.27.1.html
(Note that no code was updated after running `cargo fmt`).

[ci] Update to Rust 1.27.1.

---

components/win-users/src/account.rs

This was detected in an enterprise environment running the supervisor under a GMSA account (an AD account where AD manages the password). There account names may end in a `$`. Previously I have only seen that with local machine accounts and `LookupAccountNameW` cannot find those accounts with the trailing `$`. However when validating the GMSA account `LookupAccountNameW` will require that trailing `$`. This PR only trims the `$` if it is indeed a local machine account.
We created a small dummy test program onsite to validate this `LookupAccountNameW` behavior. I have tested this locally with made up accounts that end in a `$`.

only trim trailing $ from windows account check if it is the local machine account

---

Cargo.lock
components/win-users/src/account.rs

This updates the cargo.lock and makes a small change to `WideCString` to comply with recent changes to that lib.

update all cargo deps

---

components/core/src/os/process/linux.rs
components/core/src/os/signals/mod.rs

needed for [hab-sup controlled upgrade](https://github.com/habitat-sh/habitat/issues/5162)
Also, sneak in an unrelated comment about signal handling.

Add the ability to handle SIGHUP

---

components/core/src/package/install.rs
support/ci/lint.sh

This change reimplements the `support/ci/lint.sh` program which tries to
ensure that any Rust code contributions were prepared with the `rustfmt`
tool. The CI invocation of this programs is identical to the prior
implementation, but there are several advantages to this new approach:
* Drop reliance on flags and options in `rustfmt` to better bridge any
future changes to the program. This program attempts to use `rustfmt`
closer to how a code editor would interact with the formatter.
* Update the exit code checking of `rustfmt`, which has slightly changed
over the last 12+ months.
* Drop any remaining references to `rustfmt` version checks. Our current
approach is to use the version of `rustfmt` which ships as a component
in Rustup alongside a Rust toolchain.
* Expose explicit modes of …

[ci] Reimplement lint.sh program for better resilience.

---

components/core/src/error.rs

Inspired by https://forums.habitat.sh/t/service-group-encryption-issue/780
See also https://github.com/habitat-sh/habitat/pull/5500

Improve service group documentation to clarify optional @org part

---

components/core/src/binlink.rs

This accompanies https://github.com/habitat-sh/habitat/pull/5513

make the default windows binlink dir /hab/bin

---

Cargo.lock
components/win-users/Cargo.toml
components/win-users/src/account.rs
components/win-users/src/lib.rs

fixes https://github.com/habitat-sh/habitat/issues/5258
There are some infrequent circumstances where calls to win32 `LookupAccountNameW` will fail for reasons other than the name was not mapped to a user. For example, there may be a brief period of time after a machine has been domain joined where a call might error in:
```
The trust relationship between this workstation and the primary domain failed. (os error 1789)
```
Rather then panicing, we should simply log the error and fail the lookup returning `None`.

do not panic validating users and fail validation instead

---

.travis.yml
components/core/src/os/process/windows_child.rs
components/core/src/package/install.rs
components/core/src/package/metadata.rs
components/http-client/src/api_client.rs
support/ci/compile_libsodium.sh

https://blog.rust-lang.org/2018/09/13/Rust-1.29.html

[ci,rustfmt] Formatting due to rustfmt 0.99.1-stable in Rust 1.29.0.

---

Cargo.lock
components/core/Cargo.toml
components/core/src/fs.rs
components/core/src/lib.rs

Pretty standard dependency bumps, but also a replacement of `env::home_dir` with `dirs::home_dir`. Read commits for further information.

Update dependencies and replace deprecated code

---

components/win-users/src/lib.rs

This change allows a developer to run `cargo build`/`cargo test`/etc.
from the root of this project, regardless of which platform they are
currently running.

[win-users] Allow this crate to build on non-Windows platforms.

---

Cargo.lock
components/core/Cargo.toml
components/core/src/crypto/dpapi.rs
components/core/src/lib.rs
components/core/src/os/net/windows.rs
components/core/src/os/process/windows.rs
components/core/src/os/process/windows_child.rs
components/win-users/Cargo.toml
components/win-users/src/lib.rs
components/win-users/src/sid.rs

I had previously just bumped in the win-users crate. This includes the core crate and also removes the kernel32 and userenv crates which are included in different winapi modules.

finish off winapi update

---

components/core/src/package/install.rs
components/core/src/package/list.rs
components/core/src/package/metadata.rs
components/core/src/package/mod.rs

Pull out some useful code that was in private functions. In particular the code that can walk a package directory on disk and list all `PackageIdent`s
This will be usable as:
``` rust
use core::package;
...
...
let packages = package::all_packages(&package_path);
...
```

extract package listing functionality from PackageInstall

---

components/core/Cargo.toml
components/core/src/error.rs
components/core/src/lib.rs
components/core/src/package/list.rs

We need this in `uninstall` too.  moving it here gives a cleaner
abstraction around `INSTALL_TMP_PREFIX` which we can now make
private

Move temp_package_directory over from `hab pkg install` logic

---

components/core/src/fs.rs
components/core/src/package/install.rs
components/core/src/util/win_perm.rs

All upstream usages of `environment_for_command` end up prepending the `FS_ROOT`. I was about to add a [new usage](https://github.com/habitat-sh/habitat/pull/5813) and so it seems best to add it here.

 prepend fs_root to environment_for_command

---

components/core/src/fs.rs

moving this from the launcher code itself so we can reuse it within the uninstall command

add a helper for the launcher root path

---

Makefile
components/core/src/util/mod.rs

This is necessary for https://github.com/habitat-sh/habitat/pull/5986

Add trait for converting numeric types to i64

---

components/core/src/util/mod.rs

ToI64 has to be public if we actually want to use it elsewhere

---

Cargo.lock
components/http-client/Cargo.toml
components/http-client/src/api_client.rs
components/http-client/src/error.rs
components/http-client/src/lib.rs
components/http-client/src/net.rs
components/http-client/src/proxy.rs
components/http-client/src/util.rs

This set rolls up several changes described in the various commit messages, but the highlights include:
* Upgrading to Rust 2018 edition
* Removing some dead code and redundant `extern crate` declarations
* Removing the in-code tight coupling to Clippy in favor of using the now stable `clippy` Rustup component

[http-client] Lint and style updates

---

components/core/src/binlink.rs

On newish macs /bin is a protected driectory this change
makes binlinks go into /usr/local/bin.
Signed-off-by: Jon Morrow <jmorrow@chef.io>

Use /usr/local/bin as default bin link dir

---

.travis.yml
Cargo.lock
Makefile
components/core/Cargo.toml
components/core/src/crypto/artifact.rs
components/core/src/crypto/hash.rs
components/core/src/crypto/keys/box_key_pair.rs
components/core/src/crypto/keys/mod.rs
components/core/src/crypto/keys/sig_key_pair.rs
components/core/src/crypto/keys/sym_key.rs
components/core/src/event.rs
components/core/src/lib.rs
components/win-users/src/lib.rs

TravisCI will now run clippy and generate warnings for lints specified as `LINTS_TO_FIX` and errors for `DENIED_LINTS` as configured in the Makefile. All `clippy::correctness` lints have also been fixed as part of this PR. See https://rust-lang.github.io/rust-clippy/master/index.html.
Also remove unnecessary dependencies and fix up the make lint command.

Enable clippy in TravisCI

---

Cargo.lock
components/core/Cargo.toml
components/core/src/error.rs
components/core/src/fs.rs
components/core/src/lib.rs
components/core/src/os/users/linux.rs
components/core/src/os/users/mod.rs
components/core/src/os/users/windows.rs

This PR accompanies https://github.com/habitat-sh/habitat/pull/5866 which moves most of the hook and templating code from the supervisor into the `common` crate of the habitat repo. There was some functionality that also needed to be used commonly but seemed better suited here:
```
sup/src/fs.rs -> folded into /core/src/fs.rs
sup/src/sys/abilities -> folded into /core/src/os/users
sup/src/sys/user -> folded into /core/src/os/users
sup/src/manager/service/dir.rs -> folded into /core/src/fs.rs
```

moving some common functionality from habitat

---

Cargo.lock
Makefile
components/core/src/binlink.rs
components/core/src/channel.rs
components/core/src/config.rs
components/core/src/crypto/artifact.rs
components/core/src/crypto/keys/box_key_pair.rs
components/core/src/crypto/keys/mod.rs
components/core/src/crypto/keys/sig_key_pair.rs
components/core/src/crypto/keys/sym_key.rs
components/core/src/crypto/mod.rs
components/core/src/error.rs
components/core/src/fs.rs
components/core/src/lib.rs
components/core/src/os/ffi/windows.rs
components/core/src/os/users/linux.rs
components/core/src/output.rs
components/core/src/package/archive.rs
components/core/src/package/ident.rs
components/core/src/package/install.rs
components/core/src/package/list.rs
components/core/src/package/metadata.rs
components/core/src/package/mod.rs
components/core/src/package/plan.rs
components/core/src/service.rs
components/core/src/url.rs
components/core/src/util/sys.rs
components/http-client/src/lib.rs

This brings the Clippy lints being used in line with what we're currently using in [habitat-sh/habitat](https://github.com/habitat-sh/habitat).
Keeping them in sync helps when developing features that involve both crates.

Enable core Clippy lints

---

components/core/src/lib.rs

The potential for using `Default::default()` instead of `channel::default()` when the type representing a channel is a `&str` or `String` is a nasty latent error that the compiler will not find. To avoid it, we should use a proper type to represent channel names.
There are corresponding changes to the [habitat](https://github.com/habitat-sh/habitat/pull/6074) and [builder](https://github.com/habitat-sh/builder/pull/881) repos that must be merged after this. After that, [channel.rs](https://github.com/habitat-sh/core/blob/master/components/core/src/channel.rs) can be removed entirely.

Replace Strings and &strs with type-safe habitat_core::ChannelIdent type

---

components/core/src/lib.rs

Further work on integrating `ChannelIdent` into [habitat](https://github.com/habitat-sh/habitat/pull/6074) and [builder](https://github.com/habitat-sh/builder/pull/881) showed the need for this additional functionality. Those PRs will be blocked until this merges.

Derive necessary traits for ChannelIdent: Deserialize, Serialize, Eq, Hash

---

components/core/src/lib.rs

Not sure how this got missed. Please merge at will.

Add missing use statement for serde_derive macros

---

components/core/src/crypto/keys/box_key_pair.rs
components/core/src/event.rs

See https://github.com/habitat-sh/core/issues/15 for background.
The three commits represent three different levels of fix to `encrypt`'s return Result:
1. Change  from `Vec<u8>` to `String`
2. Use a new `WrappedSealedBox(String)` to improve safety, but add some copy overhead for some consumers
3. Make WrappedSealedBox a [copy-on-write](http://doc.rust-lang.org/1.32.0/std/borrow/enum.Cow.html) type for optimal type-safety *and* no-copy semantics, at the cost of some additional complexity.
Feedback on which approach is best is welcome.
Proposed changes for [`habitat`](https://github.com/habitat-sh/habitat/pull/6116) and [`builder`](https://github.com/habitat-sh/builder/pull/910) follow the same structure (though 2, and 3 for builder are identical).

Fix BoxKeyPair::encrypt return type

---

components/core/src/env.rs
components/core/src/lib.rs

See https://github.com/habitat-sh/habitat/issues/6168
There are some compromises here since it's not possible to directly reproduce the previous behavior within the context of the `env::Config` trait. That is, the `HAB_BLDR_CHANNEL` environment variable was used as the primary override for the ChannelIdent default, but if that was not set, it would fall back to trying the legacy environment variable: `HAB_DEPOT_CHANNEL`.
Since `env::Config` uses just one environment variable to provide a `ChannelIdent::configured_value` instance, we can't have the same behavior without putting environment variable overriding logic into `ChannelIdent::default`, which kind of defeats the purpose of the uniform `env::Config` approach.
As such, we instead make a clean break with the legacy approach:
- …

Add EnvConfig from habitat as env::Config and implement it for ChannelIdent

---

components/core/src/fs.rs

This will eventually be used by the Supervisor to remove rendered content from older package versions which have been removed in current versions.
See habitat-sh/habitat#4925 for further background and context.

Add purge_templated_content method

---

components/core/src/os/process/windows.rs

This should've happened in https://github.com/habitat-sh/core/pull/135

Add missing type-conversion to Windows code

---

components/http-client/src/api_client.rs

We need to raise the default timeout for the API client in order to accommodate large file uploads to Builder.  This (along with adjustment to the ELB idle timeout) resolves https://github.com/habitat-sh/builder/issues/961
Signed-off-by: Salim Alam <salam@chef.io>

Raise client connection timeout

---

.travis.yml

Clippy leverages `cargo check`, so running it after other tests may cause some lints to not be triggered. To increase effectiveness (and move fatal errors toward the bottom of the CI output), run clippy first.

Correctly run clippy in CI

---

components/core/src/package/archive.rs
components/core/src/package/metadata.rs

Some necessary additions for making build deps integration to the build graph.
Signed-off-by: Ian Henry <ihenry@chef.io>

Adds BUILD_DEPS and BUILD_TDEPS to available metadata types

---

components/core/src/package/archive.rs
components/core/src/package/install.rs

Not extracting the build_dep and build_tdep data into the hashmap meant not being able to actually utilize this information in any meaningful way.
Signed-off-by: Ian Henry <ihenry@chef.io>

Adds more build_dep and build_tdep functionality

---

support/ci/shared.sh

Update toolchain to nightly-2019-04-09
There were no changes when running `cargo +nightly-2019-04-09 fmt`

rustfmt update post 0.79.0 release
